call plug#begin('~/.dev-environment/vim/plugged')

" cpp 和 h 文件之间切换
Plug 'vim-scripts/a.vim'

" 多单词高亮
Plug 'vim-scripts/Mark--Karkat'

" 自动对齐
Plug 'godlygeek/tabular'

" vim 历史操作保存插件，可以在 vim 重新打开时也生效
Plug 'mbbill/undotree'

" vim 配置
Plug 'liuchengxu/space-vim-dark'

" vim 状态栏插件及其配色
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" vim 多行操作插件
Plug 'terryma/vim-multiple-cursors'

" vim 打开文件插件
Plug 'kien/ctrlp.vim'

" 括号等自动补全插件
Plug 'jiangmiao/auto-pairs'

" vim 跳转插件
Plug 'easymotion/vim-easymotion'

" vim 显示缩进对齐线
Plug 'Yggdroot/indentLine'

call plug#end()

source ~/.dev-environment/vim/vim/vimrc
source ~/.dev-environment/vim/vim/self_define_command
source ~/.dev-environment/vim/vim/plugin.conf

